# Generated by Django 5.2 on 2026-03-17 14:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HourEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('shift', models.CharField(choices=[('Day', 'Day Shift'), ('Night', 'Night Shift')], db_index=True, max_length=20)),
                ('line', models.CharField(choices=[('FL001', 'FL 001'), ('FL006', 'FL 006'), ('FL007', 'FL 007'), ('FL008', 'FL 008'), ('FL009', 'FL 009'), ('FL010', 'FL 010'), ('FL013', 'FL 013'), ('FL015', 'FL 015'), ('COPACK', 'CO-PACKING')], db_index=True, max_length=10)),
                ('aggregated_data', models.JSONField(default=list)),
                ('supervisor_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TempSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('line', models.CharField(choices=[('FL001', 'FL 001'), ('FL006', 'FL 006'), ('FL007', 'FL 007'), ('FL008', 'FL 008'), ('FL009', 'FL 009'), ('FL010', 'FL 010'), ('FL013', 'FL 013'), ('FL015', 'FL 015'), ('COPACK', 'CO-PACKING')], db_index=True, max_length=10)),
                ('shift', models.CharField(choices=[('Day', 'Day Shift'), ('Night', 'Night Shift')], db_index=True, max_length=20)),
                ('hour1', models.PositiveIntegerField(default=0)),
                ('hour2', models.PositiveIntegerField(default=0)),
                ('hour3', models.PositiveIntegerField(default=0)),
                ('hour4', models.PositiveIntegerField(default=0)),
                ('hour5', models.PositiveIntegerField(default=0)),
                ('hour6', models.PositiveIntegerField(default=0)),
                ('hour7', models.PositiveIntegerField(default=0)),
                ('hour8', models.PositiveIntegerField(default=0)),
                ('hour9', models.PositiveIntegerField(default=0)),
                ('hour10', models.PositiveIntegerField(default=0)),
                ('hour11', models.PositiveIntegerField(default=0)),
                ('hour12', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['line', 'shift'],
            },
        ),
        migrations.AlterModelOptions(
            name='jobcard',
            options={'ordering': ['-date', 'line']},
        ),
        migrations.RenameField(
            model_name='jobcard',
            old_name='back_label',
            new_name='back_label_damage',
        ),
        migrations.RenameField(
            model_name='jobcard',
            old_name='cap',
            new_name='back_label_reject',
        ),
        migrations.RenameField(
            model_name='jobcard',
            old_name='carton',
            new_name='cap_damage',
        ),
        migrations.RenameField(
            model_name='jobcard',
            old_name='front_label',
            new_name='cap_reject',
        ),
        migrations.RenameField(
            model_name='jobcard',
            old_name='jar',
            new_name='carton_damage',
        ),
        migrations.RenameField(
            model_name='jobcard',
            old_name='jar_pump',
            new_name='carton_reject',
        ),
        migrations.RenameField(
            model_name='jobcard',
            old_name='packets',
            new_name='front_label_damage',
        ),
        migrations.RenameField(
            model_name='jobcard',
            old_name='roll_on_ball',
            new_name='front_label_reject',
        ),
        migrations.RenameField(
            model_name='jobcard',
            old_name='sleeve',
            new_name='hour12',
        ),
        migrations.RenameField(
            model_name='jobcard',
            old_name='sticker',
            new_name='jar_damage',
        ),
        migrations.RenameField(
            model_name='jobcard',
            old_name='tube',
            new_name='jar_pump_damage',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='jar_pump_reject',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='jar_reject',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='packets_damage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='packets_reject',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='roll_on_ball_damage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='roll_on_ball_reject',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='sleeve_damage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='sleeve_reject',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='sticker_damage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='sticker_reject',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='tube_damage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='tube_reject',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='line',
            field=models.CharField(choices=[('FL001', 'FL 001'), ('FL006', 'FL 006'), ('FL007', 'FL 007'), ('FL008', 'FL 008'), ('FL009', 'FL 009'), ('FL010', 'FL 010'), ('FL013', 'FL 013'), ('FL015', 'FL 015'), ('COPACK', 'CO-PACKING')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day Shift'), ('Night', 'Night Shift')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='target_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['date', 'line', 'shift'], name='jobcard_job_date_3ee1f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobcard',
            constraint=models.UniqueConstraint(fields=('date', 'line', 'shift', 'wo_number'), name='unique_jobcard_per_wo_per_shift'),
        ),
        migrations.AddConstraint(
            model_name='shiftsubmission',
            constraint=models.UniqueConstraint(fields=('date', 'shift', 'line'), name='unique_shift_submission'),
        ),
        migrations.AddField(
            model_name='tempsubmission',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tempsubmission',
            index=models.Index(fields=['date', 'shift', 'line'], name='jobcard_tem_date_744f11_idx'),
        ),
        migrations.AddConstraint(
            model_name='tempsubmission',
            constraint=models.UniqueConstraint(fields=('operator', 'date', 'line', 'shift'), name='unique_operator_submission'),
        ),
    ]
