# Generated by Django 6.0.2 on 2026-03-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0002_activeshift_hourentry_shiftsubmission_tempsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeshift',
            name='last_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
