# Generated by Django 5.2 on 2026-03-25

from django.db import migrations, models


def replace_fl015_with_fl014(apps, schema_editor):
    JobCard = apps.get_model('jobcard', 'JobCard')
    TempSubmission = apps.get_model('jobcard', 'TempSubmission')
    ShiftSubmission = apps.get_model('jobcard', 'ShiftSubmission')

    # Update all existing records
    JobCard.objects.filter(line='FL015').update(line='FL014')
    TempSubmission.objects.filter(line='FL015').update(line='FL014')
    ShiftSubmission.objects.filter(line='FL015').update(line='FL014')


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0003_activeshift_last_reset'),
    ]

    operations = [
        # ✅ 1. FIRST: fix existing data
        migrations.RunPython(replace_fl015_with_fl014),

        # ✅ 2. THEN update schema choices
        migrations.AlterField(
            model_name='jobcard',
            name='line',
            field=models.CharField(
                choices=[
                    ('FL001', 'FL 001'),
                    ('FL006', 'FL 006'),
                    ('FL007', 'FL 007'),
                    ('FL008', 'FL 008'),
                    ('FL009', 'FL 009'),
                    ('FL010', 'FL 010'),
                    ('FL013', 'FL 013'),
                    ('FL014', 'FL 014'),
                    ('COPACK', 'CO-PACKING')
                ],
                db_index=True,
                max_length=10,
            ),
        ),

        migrations.AlterField(
            model_name='shiftsubmission',
            name='line',
            field=models.CharField(
                choices=[
                    ('FL001', 'FL 001'),
                    ('FL006', 'FL 006'),
                    ('FL007', 'FL 007'),
                    ('FL008', 'FL 008'),
                    ('FL009', 'FL 009'),
                    ('FL010', 'FL 010'),
                    ('FL013', 'FL 013'),
                    ('FL014', 'FL 014'),
                    ('COPACK', 'CO-PACKING')
                ],
                db_index=True,
                max_length=10,
            ),
        ),

        migrations.AlterField(
            model_name='tempsubmission',
            name='line',
            field=models.CharField(
                choices=[
                    ('FL001', 'FL 001'),
                    ('FL006', 'FL 006'),
                    ('FL007', 'FL 007'),
                    ('FL008', 'FL 008'),
                    ('FL009', 'FL 009'),
                    ('FL010', 'FL 010'),
                    ('FL013', 'FL 013'),
                    ('FL014', 'FL 014'),
                    ('COPACK', 'CO-PACKING')
                ],
                db_index=True,
                max_length=10,
            ),
        ),
    ]