# Generated by Django 5.2 on 2026-06-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('developer', 'Developer'), ('operator', 'Operator'), ('supervisor', 'Supervisor')], max_length=20),
        ),
    ]
