# Generated by Django 5.2 on 2026-07-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0007_linealert'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='user_signatures/'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='line_captain_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/line_captains/'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='supervisor_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/supervisors/'),
        ),
    ]
