# Generated by Django 6.0.2 on 2026-03-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0011_remove_jobcard_unique_jobcard_per_shift_line_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='hour12',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tempsubmission',
            name='hour12',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
